# The docker-compose configuration is for production, to use containers when developing please use the devcontainers

services:
  # Main database
  postgres-db:
    image: postgres:16-alpine
    container_name: ${APP_ENV}-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Keeps your data safe even if the container stops or restarts
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend (Gunicorn)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: ${APP_ENV}-backend
    restart: always
    depends_on:
      - postgres-db
    networks:
      - app-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: ${APP_ENV}-frontend
    restart: always
    volumes:
      # Point to the named volume so Nginx can read the assets
      - frontend-assets:/target_volume
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "test -f /target_volume/index.html"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  # Gateway
  nginx:
    image: nginx:alpine
    container_name: ${APP_ENV}-nginx
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_SSL}:443"
    volumes:
      # Mounts nginx.conf into the container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Reads the shared React files generated by the frontend container
      - frontend-assets:/usr/share/nginx/html:ro
    depends_on:
      frontend:
        # Ensures Nginx only starts after the frontend successfully finishes copying files
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    name: vantage-production-net
    driver: bridge

volumes:
  pgdata:
    name: ${APP_ENV}-pgdata
  frontend-assets:
    name: ${APP_ENV}-frontend-assets
