[mypy]
python_version = 3.12
warn_return_any = True
plugins = pydantic.mypy
warn_unused_configs = True
ignore_missing_imports = True
warn_return_any = False
exclude = ^(\.venv|venv)/

[mypy-sklearn.*]
ignore_missing_imports = True
