[mypy]
python_version = 3.12
plugins = pydantic.mypy
warn_unused_configs = True
ignore_missing_imports = True
warn_return_any = False
exclude = ^(\.venv|venv)/

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-mypy_boto3_cognito_idp.*]
ignore_missing_imports = False

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-bcrypt.*]
ignore_missing_imports = true
