version: '3.8'
services:
  # The Python/FastAPI environment
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ..:/workspaces:cached
      - pip-cache:/home/vscode/.cache/pip        
      # persists pip download cache
      - npm-cache:/home/vscode/.npm       
      # persists npm download cache
    # Keeps the container running so you can code inside it
    command: sleep infinity
    environment:
      # This points Python to the 'db' service below
      DATABASE_URL: postgresql+asyncpg://riot_user:riot_password@db:5432/riot_db
      # postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "5173:5173" # Vite (frontend)
      - "8000:8000" # FastAPI (backend)
      - "3000:3000" # Frontend (React)
      #WE Can remove 3000 if we are not using React, keeping it here for now as it is in the techstack that we use it

  # The PostgreSQL Database
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: riot_user
      POSTGRES_PASSWORD: riot_password
      POSTGRES_DB: riot_db

      # above is hardcoded for now, when movign to production MAKE SURE TO UNCOMMENT THE BELOW LINES AND REMOVE THE ABOVE LINES, so that we can use the .env file to set the values for these variables
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    # Persistent storage: data stays even if you stop the container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  pip-cache:    # pip will reuse downloaded wheels instead of fetching them again
  npm-cache:    # npm will reuse downloaded packages instead of fetching them again